name: Pull request checks for workflows

on:
    pull_request:
        branches: main
    workflow_call:

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Cache pre-commit hooks
          uses: actions/cache@v4
          with:
            path: ~/.cache/pre-commit
            key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}

        - name: Install pre-commit
          run: pip install pre-commit

        - name: Run pre-commit
          run: pre-commit run --all-files
